# syntax=docker/dockerfile:1

FROM python:3.12-alpine
WORKDIR /src
COPY src .
RUN pip install pipenv
RUN apk add --no-cache \
    gcc \
    musl-dev \
    python3-dev \
    libffi-dev \
    openssl-dev \
    cargo \
    build-base
RUN pipenv install --system --dev
