name: Python application

on:
  push

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: ../actions/python-init@main
      with:
        secrets: ${{ toJSON(secrets) }}
    - name: Install mypy and flake8
      run: |
        pip install mypy
        pip install flake8
        pip install mypy

    - name: Check for syntax errors or undefined names
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Lint with flake8
      run: |
        # The GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    - name: Lint with pylint
      run: |
        pylint ComplementsBot/bot.py
        # pylint .
    - name: Typecheck with mypy
      run: |
        mypy .

  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: Ereiarrus/ComplementsBotPy/.github/actions/python-init@main
      with:
        secrets: ${{ toJSON(secrets) }}

    - name: Install pytest
      run: |
        pip install pytest

    - name: Test with pytest
      run: |
        echo "$FIREBASE_CONFIG" > .firebase_config.json
        pytest

  deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main'  # Only deploy if this was a push to main
    steps:
    - uses: Ereiarrus/ComplementsBotPy/.github/actions/python-init@main
      with:
        secrets: ${{ toJSON(secrets) }}
    - name: deploying
      run: |
        echo "Deploying..."
