name: Python application

on:
  push

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: oNaiPs/secrets-to-env-action@v1 # exports all github secrets as environment variables
      with:
        secrets: ${{ toJSON(secrets) }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check for syntax errors or undefined names
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Lint with flake8
      run: |
        # The GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    - name: Lint with pylint
      run: |
        pylint bot.py
    - name: Typecheck with mypy
      run: |
        mypy *.py

  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - uses: oNaiPs/secrets-to-env-action@v1 # exports all github secrets as environment variables
      with:
        secrets: ${{ toJSON(secrets) }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Test with pytest
      run: |
        echo "$FIREBASE_CONFIG" > .firebase_config.json
        pytest
